// cmd/specialist-worker-template is a ready-to-copy starter project for
// building specialist Temporal workers that replace LLM agents with
// deterministic Go code.
//
// # Usage
//
//  1. Copy this directory into your own repository.
//  2. Update the module path in go.mod (replace "my-specialist-worker" with
//     your own module name, e.g. "github.com/acme/invoice-worker").
//  3. Add your handler functions (see the example below).
//  4. Register them with sw.Register("agent-name", handlerFunc).
//  5. Set SPECIALIST_TASK_QUEUE to match the task_queue in your workflow YAML.
//
// # Workflow YAML wiring
//
// In your Phaxa workflow YAML, point the agent at this worker's task queue:
//
//	agents:
//	  - name: my-agent-name          # must match sw.Register("my-agent-name", ...)
//	    task_queue: my-task-queue     # must match SPECIALIST_TASK_QUEUE
//	    # no model: needed — this handler runs in Go, not in an LLM
//
// # Environment variables
//
//	TEMPORAL_ADDRESS       Temporal frontend address (default: localhost:7233)
//	TEMPORAL_NAMESPACE     Temporal namespace        (default: default)
//	SPECIALIST_TASK_QUEUE  Task queue this worker polls (required)
package main

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"os/signal"
	"syscall"

	"github.com/asm-platform/asm/internal/specialist"
	temporalpkg "github.com/asm-platform/asm/internal/temporal"
	"github.com/asm-platform/asm/pkg/asmtypes"
)

func main() {
	// ── Configuration ─────────────────────────────────────────────────────────
	temporalAddr := envOr("TEMPORAL_ADDRESS", "localhost:7233")
	temporalNS   := envOr("TEMPORAL_NAMESPACE", "default")
	taskQueue    := envOr("SPECIALIST_TASK_QUEUE", "")
	if taskQueue == "" {
		slog.Error("SPECIALIST_TASK_QUEUE environment variable is required")
		os.Exit(1)
	}

	logLevel := slog.LevelInfo
	if os.Getenv("LOG_LEVEL") == "debug" {
		logLevel = slog.LevelDebug
	}
	slog.SetDefault(slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{Level: logLevel})))

	// ── Register handlers ─────────────────────────────────────────────────────
	// Replace the example handler below with your own.
	// Each name must match the "name" field of the agent in the workflow YAML.
	sw := specialist.New(taskQueue)
	sw.Register("my-agent-name", myAgentHandler)
	// sw.Register("another-agent", anotherHandler)

	// ── Connect to Temporal ───────────────────────────────────────────────────
	temporalClient, err := temporalpkg.NewClient(temporalAddr, temporalNS)
	if err != nil {
		slog.Error("Failed to connect to Temporal", "error", err)
		os.Exit(1)
	}
	defer temporalClient.Close()

	w := sw.Build(temporalClient)

	// ── Graceful shutdown ─────────────────────────────────────────────────────
	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, syscall.SIGINT, syscall.SIGTERM)
	interruptCh := make(chan interface{}, 1)
	go func() {
		<-sigCh
		interruptCh <- struct{}{}
	}()

	slog.Info("Specialist worker starting",
		"queue", taskQueue,
		"temporal", temporalAddr,
		"handlers", sw.Handlers(),
	)
	if err := w.Run(interruptCh); err != nil {
		slog.Error("Worker run error", "error", err)
		os.Exit(1)
	}
	slog.Info("Specialist worker stopped")
}

// ── Example handler ───────────────────────────────────────────────────────────
//
// Replace this with your own deterministic logic.
// The function name, signature, and return type must match HandlerFunc:
//
//	func(ctx context.Context, bb map[string]interface{}) (*asmtypes.AgentOutput, error)
//
// Paste code generated by the Phaxa Designer "Generate Code" button here.
func myAgentHandler(_ context.Context, bb map[string]interface{}) (*asmtypes.AgentOutput, error) {
	// Access blackboard fields with type assertions.
	// JSON numbers always decode as float64.
	amount, _ := bb["amount"].(float64)

	if amount <= 0 {
		return &asmtypes.AgentOutput{
			Trigger:   "invalid",
			Reasoning: fmt.Sprintf("amount must be positive, got %v", amount),
			BlackboardUpdates: map[string]interface{}{
				"error": "amount must be positive",
			},
		}, nil
	}

	return &asmtypes.AgentOutput{
		Trigger:   "ok",
		Reasoning: fmt.Sprintf("amount %v is valid", amount),
		BlackboardUpdates: map[string]interface{}{
			"validated": true,
		},
	}, nil
}

func envOr(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}
